dist: trusty

jobs:
  include:
    - stage: build Nginx docker image
      script:
      - docker build -t mynginx:latest .
      - docker images
      - docker run --rm mynginx:latest "service nginx start; curl http://localhost:80/"
    