sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "curl localhost:80;"
  - docker ps -a

script:
  - "echo hi"
