dist: trusty

jobs:
  include:
    - stage: build Nginx docker image
      script:
      - docker build -t mynginx:latest .
      - docker images
    - stage: test
      script: docker run --rm mynginx:latest "service nginx start"
    - script: docker run --rm mynginx:latest "curl http://localhost"
